### ISSUE TITLE
ha3g device tree los 16.0 not working makefile errors AndroidProducts.mk 

### ISSUE THREAD

**Issue by IntelliPerson** [exynos5420/android_device_samsung_ha3g#3]
ha3g device tree los 16.0 not working makefile errors AndroidProducts.mk

**Comment by thompatry** [comment]
Hello,

Currently no one on our team has a ha3g device so we unable to support it. If you would like to provide one for our team, please feel free to do so. It is very difficult to support devices we do not have our hands on. 

If you would like to submit code changes, please push them to https://review.exynos5420.com/

Thanks
